# Generated by Django 5.0.1 on 2024-01-07 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_state_customer_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='District',
            new_name='district',
        ),
    ]
